# 基本概念
C++异常处理机制是用来处理程序运行过程中可能出现的错误或异常情况的机制。它通过将错误检测和错误处理分离，提高代码的健壮性和可读性。

C++的异常处理是通过try、throw和catch关键字实现的。
# 关键元素
throw: 用于抛出异常。当程序遇到错误或异常时，可以使用throw抛出异常对象。

try: 用于包裹可能引发异常的代码块。如果在try块中的代码抛出异常，程序将跳转到相应的catch块进行处理，必须与至少一个 catch 配对。

catch: 用于捕获和处理异常。catch块会捕获try块中抛出的异常，并进行相应的处理。**catch (...)** 捕获所有异常，作为最后手段。
# 工作流程
- 正常执行：程序按照正常的逻辑执行try块中的代码。
- 异常抛出：当程序在try块中遇到异常条件时，throw会抛出异常。
- 异常捕获：程序会跳转到对应的catch块来捕获并处理这个异常。
- 异常处理：catch块中的代码将处理异常，比如打印错误信息、进行修复等。
- 程序继续：异常处理完毕后，程序可以继续执行后续代码。
~~~
#include <iostream>
#include <stdexcept>  // 用于标准异常类
void divide(int a, int b) {
    if (b == 0) {
        // 抛出异常
        throw std::invalid_argument("除数不能为零！");
    }
    std::cout << "结果: " << a / b << std::endl;
}
int main() {
    try {
        divide(10, 0);  // 这里会抛出异常
    } catch (const std::invalid_argument& e) {
        // 捕获异常并处理
        std::cout << "捕获到异常: " << e.what() << std::endl;
    }
    std::cout << "程序继续执行" << std::endl;
    return 0;
}
~~~
